/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cookieclickercosmico;

/**
 *
 * @author sowbo
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private GameState estado;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(GameState estado) {
        this.estado = estado;
        initComponents();
        
        
        
        // 1. Criamos as telas passando o GameState para elas!
        // (Você vai precisar arrumar o construtor dessas telas depois para receber o estado)
        cookieclickercosmico.Telas.TelaInicio telaInicio = new cookieclickercosmico.Telas.TelaInicio(); 
        cookieclickercosmico.Telas.TelaLoja telaLoja = new cookieclickercosmico.Telas.TelaLoja();
        cookieclickercosmico.Telas.TelaConquistas telaConquistas = new cookieclickercosmico.Telas.TelaConquistas();
        cookieclickercosmico.Telas.TelaPerfil telaPerfil = new cookieclickercosmico.Telas.TelaPerfil();

        // 2. Adicionamos elas no seu painelCartas (o baralho), dando o apelido de cada uma
        painelCartas.add(telaInicio, "cardInicio");
        painelCartas.add(telaLoja, "cardLoja");
        painelCartas.add(telaConquistas, "cardConquistas");
        painelCartas.add(telaPerfil, "cardPerfil");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCartas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelCartasLayout = new javax.swing.GroupLayout(painelCartas);
        painelCartas.setLayout(painelCartasLayout);
        painelCartasLayout.setHorizontalGroup(
            painelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        painelCartasLayout.setVerticalGroup(
            painelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCartas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelCartas;
    // End of variables declaration//GEN-END:variables
}
