/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cookieclickercosmico.Telas;

import cookieclickercosmico.Entidades.Achievement;
import cookieclickercosmico.GameState;

/**
 *
 * @author sowbo
 */
public class TelaConquistas extends javax.swing.JPanel {

    private GameState estado; // Variável para guardar o motor do jogo

    public TelaConquistas(GameState estado) {
        this.estado = estado;
        initComponents();
        atualizarConquistas();
    }
    
    public void atualizarConquistas() {
        painelContainerConquistas.removeAll();
        painelContainerConquistas.setLayout(new javax.swing.BoxLayout(painelContainerConquistas, javax.swing.BoxLayout.Y_AXIS));

        for (Achievement c : estado.getConquistas()) {
            javax.swing.JPanel painelC = new javax.swing.JPanel(new java.awt.BorderLayout());
            javax.swing.JLabel lbl = new javax.swing.JLabel();
            painelC.setMaximumSize(new java.awt.Dimension(800, 80));

            // Estilo visual igual as outras telas
            if (c.isDesbloqueada()) {
                painelC.setBackground(new java.awt.Color(20, 10, 60)); // Roxo escuro
                painelC.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 2, true), // Borda dourada
                    javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
                ));
                lbl.setText("<html><body style='width: 250px;'>" +
                           "<b style='font-size:14px; color:white;'>🏆 " + c.getNome() + "</b><br>" +
                           "<i style='color: #FFD700; font-size:11px;'>" + c.getDescricao() + "</i>" +
                           "</body></html>");            
            } else {
                painelC.setBackground(new java.awt.Color(120, 120, 150)); // Cinza roxeado bloqueado
                painelC.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 150, 180), 2, true),
                    javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
                ));
                lbl.setText("<html><body style='width: 250px;'>" +
                           "<b style='font-size:14px; color:#E0E0E0;'>🔒 " + c.getNome() + "</b><br>" +
                           "<i style='color: #333333; font-size:11px;'>" + c.getDescricao() + "</i>" +
                           "</body></html>");
            } 

            painelC.add(lbl, java.awt.BorderLayout.CENTER);
            painelContainerConquistas.add(painelC);
            painelContainerConquistas.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10))); // Espaçamento
        }

        painelContainerConquistas.revalidate();
        painelContainerConquistas.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelContainerConquistas = new javax.swing.JPanel();

        painelContainerConquistas.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout painelContainerConquistasLayout = new javax.swing.GroupLayout(painelContainerConquistas);
        painelContainerConquistas.setLayout(painelContainerConquistasLayout);
        painelContainerConquistasLayout.setHorizontalGroup(
            painelContainerConquistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelContainerConquistasLayout.setVerticalGroup(
            painelContainerConquistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelContainerConquistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelContainerConquistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelContainerConquistas;
    // End of variables declaration//GEN-END:variables
}
